version: "3"

services:
  db:
    container_name: db
    image: mysql:latest
    volumes:
      - mysql_data_dev:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dev_db
      MYSQL_ROOT_PASSWORD: root
    restart: always      
    ports:
      - 3306:3306

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8080:8000
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]
    volumes:
      - ./backend/:/backend/
    expose:
      - 8080
    # env_file:
    #   - ./settings/dev/.env.dev
    depends_on:
      - db


  # frontend:
  #   container_name: dev-frontend
  #   build:
  #     context: ./frontend
  #   command: [ "yarn", "start" ]
  #   ports:
  #     - 80:3000
  #   volumes:
  #     - ./frontend/:/frontend
  #     - ./frontend/node_modules/:/frontend/node_modules
  #   environment:
  #     - CI=true
  #     - CHOKIDAR_USEPOLLING=true
  #     - REACT_APP_BACKEND_URL=http://localhost:8080
  #   tty: true

volumes:
  mysql_data_dev: null
